/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

float *
suma_1_svc(struct operadores *argp, struct svc_req *rqstp)
{
	static float  result;

	result = (argp->numA) + (argp->numB);

	return &result;
}

float *
resta_1_svc(struct operadores *argp, struct svc_req *rqstp)
{
	static float  result;

	result = (argp->numA) - (argp->numB);

	return &result;
}

float *
multiplicacion_1_svc(struct operadores *argp, struct svc_req *rqstp)
{
	static float  result;

	result = (argp->numA) * (argp->numB);

	return &result;
}

float *
division_1_svc(struct operadores *argp, struct svc_req *rqstp)
{
	static float  result;

	result = (argp->numA) / (argp->numB);

	return &result;
}
