/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"
#include <stdio.h>
#include <stdlib.h>

void calculadora_1(char *host) {
    CLIENT *clnt;
    float *result;
    struct operadores args;
    int opcion;

#ifndef DEBUG
    clnt = clnt_create(host, CALCULADORA, CALC_1, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror(host);
        exit(1);
    }
#endif /* DEBUG */

    do {
        printf("\n----------------------------------------------\n");
        printf("   CALCULADORA DISTRIBUIDA RPC\n");
        printf("----------------------------------------------\n");
        printf("1. Suma\n");
        printf("2. Resta\n");
        printf("3. Multiplicacion\n");
        printf("4. Division\n");
        printf("5. Salir\n");
        printf("Elige una opcion: ");
        scanf("%d", &opcion);

        if (opcion >= 1 && opcion <= 4) {
            printf("Ingresa el primer numero: ");
            scanf("%f", &args.numA);
            printf("Ingresa el segundo numero: ");
            scanf("%f", &args.numB);

            switch (opcion) {
                case 1:
                    result = suma_1(&args, clnt);
                    break;
                case 2:
                    result = resta_1(&args, clnt);
                    break;
                case 3:
                    result = multiplicacion_1(&args, clnt);
                    break;
                case 4:
                    result = division_1(&args, clnt);
                    break;
            }

            if (result == NULL) {
                clnt_perror(clnt, "Llamada RPC falló");
            } else {
                printf("Resultado: %.2f\n", *result);
            }
        }
    } while (opcion != 5);

#ifndef DEBUG
    clnt_destroy(clnt);
#endif /* DEBUG */
}

int main(int argc, char *argv[]) {
    char *host;

    if (argc < 2) {
        printf("Uso: %s <host_servidor>\n", argv[0]);
        exit(1);
    }
    host = argv[1];
    calculadora_1(host);

    return 0;
}

