/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"

bool_t
xdr_operadores (XDR *xdrs, operadores *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->numA))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->numB))
		 return FALSE;
	return TRUE;
}
