/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct operadores {
	float numA;
	float numB;
};
typedef struct operadores operadores;

#define CALCULADORA 1
#define CALC_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define suma 1
extern  float * suma_1(struct operadores *, CLIENT *);
extern  float * suma_1_svc(struct operadores *, struct svc_req *);
#define resta 2
extern  float * resta_1(struct operadores *, CLIENT *);
extern  float * resta_1_svc(struct operadores *, struct svc_req *);
#define multiplicacion 3
extern  float * multiplicacion_1(struct operadores *, CLIENT *);
extern  float * multiplicacion_1_svc(struct operadores *, struct svc_req *);
#define division 4
extern  float * division_1(struct operadores *, CLIENT *);
extern  float * division_1_svc(struct operadores *, struct svc_req *);
extern int calculadora_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define suma 1
extern  float * suma_1();
extern  float * suma_1_svc();
#define resta 2
extern  float * resta_1();
extern  float * resta_1_svc();
#define multiplicacion 3
extern  float * multiplicacion_1();
extern  float * multiplicacion_1_svc();
#define division 4
extern  float * division_1();
extern  float * division_1_svc();
extern int calculadora_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_operadores (XDR *, operadores*);

#else /* K&R C */
extern bool_t xdr_operadores ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
